#!/usr/bin/env bash
# This script displays "Best School" 10 times, saying "Hi" on the 9th iteration

# Initializing counter
counter=1

# Using a while loop to display "Best School" 10 times
while [ $counter -le 10 ]; do
    # Checking if it's the 9th iteration
    if [ $counter -eq 9 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi

    # Incrementing the counter
    ((counter++))
done
