#!/usr/bin/env bash
# This script displays numbers with superstitious messages for specific iterations

# Initializing counter
counter=1

# Using a while loop to display messages for numbers 1 to 20
while [ $counter -le 20 ]; do
    # Using a case statement to check the current iteration
    case $counter in
        4)
            echo "$counter"
            echo "bad luck from China"
            ;;
        9)
            echo "$counter"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac

    # Incrementing the counter
    ((counter++))
done
