#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Initializing variables
hours=0

# Using a while loop to display time for 12 hours and 59 minutes
while [ $hours -le 12 ]; do
    echo "Hour: $hours"
    
    minutes=1
    while [ $minutes -le 59 ]; do
        echo $minutes
        ((minutes++))
        
        # Checking if the total lines displayed reach 70
        total_lines=$((hours * 60 + minutes))
        if [ $total_lines -ge 70 ]; then
            exit
        fi
    done
    
    ((hours++))
done
